/**
 * Writes public/sw.js for production — proxies /api/* to the Render backend (same-origin).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import dotenv from "dotenv";

const root = resolve(fileURLToPath(import.meta.url), "..", "..");
dotenv.config({ path: resolve(root, ".env.production") });

const apiOrigin = (
  process.env.VITE_API_BASE_URL || "https://toolcrate-backend-500j.onrender.com"
).replace(/\/$/, "");

const sw = `/* Generated by scripts/generate-api-sw.js — do not edit */
const API_ORIGIN = ${JSON.stringify(apiOrigin)};

self.addEventListener("install", () => self.skipWaiting());
self.addEventListener("activate", (event) => event.waitUntil(self.clients.claim()));

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  if (url.origin !== self.location.origin || !url.pathname.startsWith("/api/")) return;

  const target = API_ORIGIN + url.pathname + url.search;
  event.respondWith(
    fetch(target, {
      method: event.request.method,
      headers: event.request.headers,
      body: event.request.method === "GET" || event.request.method === "HEAD" ? undefined : event.request.body,
      mode: "cors",
      credentials: "omit",
    })
  );
});
`;

writeFileSync(resolve(root, "public/sw.js"), sw);
console.log(`Wrote public/sw.js → proxy /api/* to ${apiOrigin}`);
